name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [5, 6]
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: ${{ matrix.redis-version }}
    - name: Install dependencies
      run: shards install --ignore-crystal-version
    - name: Lint
      run: ./bin/ameba
    - name: Format
      run: crystal tool format --check
    - name: Run tests
      run: crystal spec --error-trace -v
